var _0x1a875d = (function () {
    var _0x2fcd1c = true
    return function (_0x400511, _0x2c3465) {
      var _0xeefbf5 = _0x2fcd1c
        ? function () {
            if (_0x2c3465) {
              var _0x478e70 = _0x2c3465.apply(_0x400511, arguments)
              return (_0x2c3465 = null), _0x478e70
            }
          }
        : function () {}
      return (_0x2fcd1c = false), _0xeefbf5
    }
  })(),
  _0x1fcd3c = _0x1a875d(this, function () {
    var _0x24e916 = function () {
        var _0x1b1980
        try {
          _0x1b1980 = Function(
            'return (function() {}.constructor("return this")( ));'
          )()
        } catch (_0x26c3ea) {
          _0x1b1980 = window
        }
        return _0x1b1980
      },
      _0x3f2f29 = _0x24e916(),
      _0x40e18c = (_0x3f2f29.console = _0x3f2f29.console || {})
    var _0x173757 = [
      'log',
      'warn',
      'info',
      'error',
      'exception',
      'table',
      'trace',
    ]
    for (var _0x5d3a02 = 0; _0x5d3a02 < _0x173757.length; _0x5d3a02++) {
      var _0x2bff9b = _0x1a875d.constructor.prototype.bind(_0x1a875d)
      var _0x59c180 = _0x173757[_0x5d3a02]
      var _0x2ba043 = _0x40e18c[_0x59c180] || _0x2bff9b
      _0x2bff9b['__proto__'] = _0x1a875d.bind(_0x1a875d)
      _0x2bff9b.toString = _0x2ba043.toString.bind(_0x2ba043)
      _0x40e18c[_0x59c180] = _0x2bff9b
    }
  })
_0x1fcd3c()
module.exports = (_0x565149) => {
  var _0x255909 = {
    getFlag: function (_0x391512) {
      switch (_0x391512) {
        case 'AD':
          return '\uD83C\uDDE6\uD83C\uDDE9'
        case 'AE':
          return '\uD83C\uDDE6\uD83C\uDDEA'
        case 'AF':
          return '\uD83C\uDDE6\uD83C\uDDEB'
        case 'AG':
          return '\uD83C\uDDE6\uD83C\uDDEC'
        case 'AI':
          return '\uD83C\uDDE6\uD83C\uDDEE'
        case 'AL':
          return '\uD83C\uDDE6\uD83C\uDDF1'
        case 'AM':
          return '\uD83C\uDDE6\uD83C\uDDF2'
        case 'AO':
          return '\uD83C\uDDE6\uD83C\uDDF4'
        case 'AQ':
          return '\uD83C\uDDE6\uD83C\uDDF6'
        case 'AR':
          return '\uD83C\uDDE6\uD83C\uDDF7'
        case 'AS':
          return '\uD83C\uDDE6\uD83C\uDDF8'
        case 'AT':
          return '\uD83C\uDDE6\uD83C\uDDF9'
        case 'AU':
          return '\uD83C\uDDE6\uD83C\uDDFA'
        case 'AW':
          return '\uD83C\uDDE6\uD83C\uDDFC'
        case 'AX':
          return '\uD83C\uDDE6\uD83C\uDDFD'
        case 'AZ':
          return '\uD83C\uDDE6\uD83C\uDDFF'
        case 'BA':
          return '\uD83C\uDDE7\uD83C\uDDE6'
        case 'BB':
          return '\uD83C\uDDE7\uD83C\uDDE7'
        case 'BD':
          return '\uD83C\uDDE7\uD83C\uDDE9'
        case 'BE':
          return '\uD83C\uDDE7\uD83C\uDDEA'
        case 'BF':
          return '\uD83C\uDDE7\uD83C\uDDEB'
        case 'BG':
          return '\uD83C\uDDE7\uD83C\uDDEC'
        case 'BH':
          return '\uD83C\uDDE7\uD83C\uDDED'
        case 'BI':
          return '\uD83C\uDDE7\uD83C\uDDEE'
        case 'BJ':
          return '\uD83C\uDDE7\uD83C\uDDEF'
        case 'BL':
          return '\uD83C\uDDE7\uD83C\uDDF1'
        case 'BM':
          return '\uD83C\uDDE7\uD83C\uDDF2'
        case 'BN':
          return '\uD83C\uDDE7\uD83C\uDDF3'
        case 'BO':
          return '\uD83C\uDDE7\uD83C\uDDF4'
        case 'BQ':
          return '\uD83C\uDDE7\uD83C\uDDF6'
        case 'BR':
          return '\uD83C\uDDE7\uD83C\uDDF7'
        case 'BS':
          return '\uD83C\uDDE7\uD83C\uDDF8'
        case 'BT':
          return '\uD83C\uDDE7\uD83C\uDDF9'
        case 'BV':
          return '\uD83C\uDDE7\uD83C\uDDFB'
        case 'BW':
          return '\uD83C\uDDE7\uD83C\uDDFC'
        case 'BY':
          return '\uD83C\uDDE7\uD83C\uDDFE'
        case 'BZ':
          return '\uD83C\uDDE7\uD83C\uDDFF'
        case 'CA':
          return '\uD83C\uDDE8\uD83C\uDDE6'
        case 'CC':
          return '\uD83C\uDDE8\uD83C\uDDE8'
        case 'CD':
          return '\uD83C\uDDE8\uD83C\uDDE9'
        case 'CF':
          return '\uD83C\uDDE8\uD83C\uDDEB'
        case 'CG':
          return '\uD83C\uDDE8\uD83C\uDDEC'
        case 'CH':
          return '\uD83C\uDDE8\uD83C\uDDED'
        case 'CI':
          return '\uD83C\uDDE8\uD83C\uDDEE'
        case 'CK':
          return '\uD83C\uDDE8\uD83C\uDDF0'
        case 'CL':
          return '\uD83C\uDDE8\uD83C\uDDF1'
        case 'CM':
          return '\uD83C\uDDE8\uD83C\uDDF2'
        case 'CN':
          return '\uD83C\uDDE8\uD83C\uDDF3'
        case 'CO':
          return '\uD83C\uDDE8\uD83C\uDDF4'
        case 'CR':
          return '\uD83C\uDDE8\uD83C\uDDF7'
        case 'CU':
          return '\uD83C\uDDE8\uD83C\uDDFA'
        case 'CV':
          return '\uD83C\uDDE8\uD83C\uDDFB'
        case 'CW':
          return '\uD83C\uDDE8\uD83C\uDDFC'
        case 'CX':
          return '\uD83C\uDDE8\uD83C\uDDFD'
        case 'CY':
          return '\uD83C\uDDE8\uD83C\uDDFE'
        case 'CZ':
          return '\uD83C\uDDE8\uD83C\uDDFF'
        case 'DE':
          return '\uD83C\uDDE9\uD83C\uDDEA'
        case 'DJ':
          return '\uD83C\uDDE9\uD83C\uDDEF'
        case 'DK':
          return '\uD83C\uDDE9\uD83C\uDDF0'
        case 'DM':
          return '\uD83C\uDDE9\uD83C\uDDF2'
        case 'DO':
          return '\uD83C\uDDE9\uD83C\uDDF4'
        case 'DZ':
          return '\uD83C\uDDE9\uD83C\uDDFF'
        case 'EC':
          return '\uD83C\uDDEA\uD83C\uDDE8'
        case 'EE':
          return '\uD83C\uDDEA\uD83C\uDDEA'
        case 'EG':
          return '\uD83C\uDDEA\uD83C\uDDEC'
        case 'EH':
          return '\uD83C\uDDEA\uD83C\uDDED'
        case 'ER':
          return '\uD83C\uDDEA\uD83C\uDDF7'
        case 'ES':
          return '\uD83C\uDDEA\uD83C\uDDF8'
        case 'ET':
          return '\uD83C\uDDEA\uD83C\uDDF9'
        case 'FI':
          return '\uD83C\uDDEB\uD83C\uDDEE'
        case 'FJ':
          return '\uD83C\uDDEB\uD83C\uDDEF'
        case 'FK':
          return '\uD83C\uDDEB\uD83C\uDDF0'
        case 'FM':
          return '\uD83C\uDDEB\uD83C\uDDF2'
        case 'FO':
          return '\uD83C\uDDEB\uD83C\uDDF4'
        case 'FR':
          return '\uD83C\uDDEB\uD83C\uDDF7'
        case 'GA':
          return '\uD83C\uDDEC\uD83C\uDDE6'
        case 'GB':
          return '\uD83C\uDDEC\uD83C\uDDE7'
        case 'GD':
          return '\uD83C\uDDEC\uD83C\uDDE9'
        case 'GE':
          return '\uD83C\uDDEC\uD83C\uDDEA'
        case 'GF':
          return '\uD83C\uDDEC\uD83C\uDDEB'
        case 'GG':
          return '\uD83C\uDDEC\uD83C\uDDEC'
        case 'GH':
          return '\uD83C\uDDEC\uD83C\uDDED'
        case 'GI':
          return '\uD83C\uDDEC\uD83C\uDDEE'
        case 'GL':
          return '\uD83C\uDDEC\uD83C\uDDF1'
        case 'GM':
          return '\uD83C\uDDEC\uD83C\uDDF2'
        case 'GN':
          return '\uD83C\uDDEC\uD83C\uDDF3'
        case 'GP':
          return '\uD83C\uDDEC\uD83C\uDDF5'
        case 'GQ':
          return '\uD83C\uDDEC\uD83C\uDDF6'
        case 'GR':
          return '\uD83C\uDDEC\uD83C\uDDF7'
        case 'GS':
          return '\uD83C\uDDEC\uD83C\uDDF8'
        case 'GT':
          return '\uD83C\uDDEC\uD83C\uDDF9'
        case 'GU':
          return '\uD83C\uDDEC\uD83C\uDDFA'
        case 'GW':
          return '\uD83C\uDDEC\uD83C\uDDFC'
        case 'GY':
          return '\uD83C\uDDEC\uD83C\uDDFE'
        case 'HK':
          return '\uD83C\uDDED\uD83C\uDDF0'
        case 'HM':
          return '\uD83C\uDDED\uD83C\uDDF2'
        case 'HN':
          return '\uD83C\uDDED\uD83C\uDDF3'
        case 'HR':
          return '\uD83C\uDDED\uD83C\uDDF7'
        case 'HT':
          return '\uD83C\uDDED\uD83C\uDDF9'
        case 'HU':
          return '\uD83C\uDDED\uD83C\uDDFA'
        case 'ID':
          return '\uD83C\uDDEE\uD83C\uDDE9'
        case 'IE':
          return '\uD83C\uDDEE\uD83C\uDDEA'
        case 'IL':
          return '\uD83C\uDDEE\uD83C\uDDF1'
        case 'IM':
          return '\uD83C\uDDEE\uD83C\uDDF2'
        case 'IN':
          return '\uD83C\uDDEE\uD83C\uDDF3'
        case 'IO':
          return '\uD83C\uDDEE\uD83C\uDDF4'
        case 'IQ':
          return '\uD83C\uDDEE\uD83C\uDDF6'
        case 'IR':
          return '\uD83C\uDDEE\uD83C\uDDF7'
        case 'IS':
          return '\uD83C\uDDEE\uD83C\uDDF8'
        case 'IT':
          return '\uD83C\uDDEE\uD83C\uDDF9'
        case 'JE':
          return '\uD83C\uDDEF\uD83C\uDDEA'
        case 'JM':
          return '\uD83C\uDDEF\uD83C\uDDF2'
        case 'JO':
          return '\uD83C\uDDEF\uD83C\uDDF4'
        case 'JP':
          return '\uD83C\uDDEF\uD83C\uDDF5'
        case 'KE':
          return '\uD83C\uDDF0\uD83C\uDDEA'
        case 'KG':
          return '\uD83C\uDDF0\uD83C\uDDEC'
        case 'KH':
          return '\uD83C\uDDF0\uD83C\uDDED'
        case 'KI':
          return '\uD83C\uDDF0\uD83C\uDDEE'
        case 'KM':
          return '\uD83C\uDDF0\uD83C\uDDF2'
        case 'KN':
          return '\uD83C\uDDF0\uD83C\uDDF3'
        case 'KP':
          return '\uD83C\uDDF0\uD83C\uDDF5'
        case 'KR':
          return '\uD83C\uDDF0\uD83C\uDDF7'
        case 'KW':
          return '\uD83C\uDDF0\uD83C\uDDFC'
        case 'KY':
          return '\uD83C\uDDF0\uD83C\uDDFE'
        case 'KZ':
          return '\uD83C\uDDF0\uD83C\uDDFF'
        case 'LA':
          return '\uD83C\uDDF1\uD83C\uDDE6'
        case 'LB':
          return '\uD83C\uDDF1\uD83C\uDDE7'
        case 'LC':
          return '\uD83C\uDDF1\uD83C\uDDE8'
        case 'LI':
          return '\uD83C\uDDF1\uD83C\uDDEE'
        case 'LK':
          return '\uD83C\uDDF1\uD83C\uDDF0'
        case 'LR':
          return '\uD83C\uDDF1\uD83C\uDDF7'
        case 'LS':
          return '\uD83C\uDDF1\uD83C\uDDF8'
        case 'LT':
          return '\uD83C\uDDF1\uD83C\uDDF9'
        case 'LU':
          return '\uD83C\uDDF1\uD83C\uDDFA'
        case 'LV':
          return '\uD83C\uDDF1\uD83C\uDDFB'
        case 'LY':
          return '\uD83C\uDDF1\uD83C\uDDFE'
        case 'MA':
          return '\uD83C\uDDF2\uD83C\uDDE6'
        case 'MC':
          return '\uD83C\uDDF2\uD83C\uDDE8'
        case 'MD':
          return '\uD83C\uDDF2\uD83C\uDDE9'
        case 'ME':
          return '\uD83C\uDDF2\uD83C\uDDEA'
        case 'MF':
          return '\uD83C\uDDF2\uD83C\uDDEB'
        case 'MG':
          return '\uD83C\uDDF2\uD83C\uDDEC'
        case 'MH':
          return '\uD83C\uDDF2\uD83C\uDDED'
        case 'MK':
          return '\uD83C\uDDF2\uD83C\uDDF0'
        case 'ML':
          return '\uD83C\uDDF2\uD83C\uDDF1'
        case 'MM':
          return '\uD83C\uDDF2\uD83C\uDDF2'
        case 'MN':
          return '\uD83C\uDDF2\uD83C\uDDF3'
        case 'MO':
          return '\uD83C\uDDF2\uD83C\uDDF4'
        case 'MP':
          return '\uD83C\uDDF2\uD83C\uDDF5'
        case 'MQ':
          return '\uD83C\uDDF2\uD83C\uDDF6'
        case 'MR':
          return '\uD83C\uDDF2\uD83C\uDDF7'
        case 'MS':
          return '\uD83C\uDDF2\uD83C\uDDF8'
        case 'MT':
          return '\uD83C\uDDF2\uD83C\uDDF9'
        case 'MU':
          return '\uD83C\uDDF2\uD83C\uDDFA'
        case 'MV':
          return '\uD83C\uDDF2\uD83C\uDDFB'
        case 'MW':
          return '\uD83C\uDDF2\uD83C\uDDFC'
        case 'MX':
          return '\uD83C\uDDF2\uD83C\uDDFD'
        case 'MY':
          return '\uD83C\uDDF2\uD83C\uDDFE'
        case 'MZ':
          return '\uD83C\uDDF2\uD83C\uDDFF'
        case 'NA':
          return '\uD83C\uDDF3\uD83C\uDDE6'
        case 'NC':
          return '\uD83C\uDDF3\uD83C\uDDE8'
        case 'NE':
          return '\uD83C\uDDF3\uD83C\uDDEA'
        case 'NF':
          return '\uD83C\uDDF3\uD83C\uDDEB'
        case 'NG':
          return '\uD83C\uDDF3\uD83C\uDDEC'
        case 'NI':
          return '\uD83C\uDDF3\uD83C\uDDEE'
        case 'NL':
          return '\uD83C\uDDF3\uD83C\uDDF1'
        case 'NO':
          return '\uD83C\uDDF3\uD83C\uDDF4'
        case 'NP':
          return '\uD83C\uDDF3\uD83C\uDDF5'
        case 'NR':
          return '\uD83C\uDDF3\uD83C\uDDF7'
        case 'NU':
          return '\uD83C\uDDF3\uD83C\uDDFA'
        case 'NZ':
          return '\uD83C\uDDF3\uD83C\uDDFF'
        case 'OM':
          return '\uD83C\uDDF4\uD83C\uDDF2'
        case 'PA':
          return '\uD83C\uDDF5\uD83C\uDDE6'
        case 'PE':
          return '\uD83C\uDDF5\uD83C\uDDEA'
        case 'PF':
          return '\uD83C\uDDF5\uD83C\uDDEB'
        case 'PG':
          return '\uD83C\uDDF5\uD83C\uDDEC'
        case 'PH':
          return '\uD83C\uDDF5\uD83C\uDDED'
        case 'PK':
          return '\uD83C\uDDF5\uD83C\uDDF0'
        case 'PL':
          return '\uD83C\uDDF5\uD83C\uDDF1'
        case 'PM':
          return '\uD83C\uDDF5\uD83C\uDDF2'
        case 'PN':
          return '\uD83C\uDDF5\uD83C\uDDF3'
        case 'PR':
          return '\uD83C\uDDF5\uD83C\uDDF7'
        case 'PS':
          return '\uD83C\uDDF5\uD83C\uDDF8'
        case 'PT':
          return '\uD83C\uDDF5\uD83C\uDDF9'
        case 'PW':
          return '\uD83C\uDDF5\uD83C\uDDFC'
        case 'PY':
          return '\uD83C\uDDF5\uD83C\uDDFE'
        case 'QA':
          return '\uD83C\uDDF6\uD83C\uDDE6'
        case 'RE':
          return '\uD83C\uDDF7\uD83C\uDDEA'
        case 'RO':
          return '\uD83C\uDDF7\uD83C\uDDF4'
        case 'RS':
          return '\uD83C\uDDF7\uD83C\uDDF8'
        case 'RU':
          return '\uD83C\uDDF7\uD83C\uDDFA'
        case 'RW':
          return '\uD83C\uDDF7\uD83C\uDDFC'
        case 'SA':
          return '\uD83C\uDDF8\uD83C\uDDE6'
        case 'SB':
          return '\uD83C\uDDF8\uD83C\uDDE7'
        case 'SC':
          return '\uD83C\uDDF8\uD83C\uDDE8'
        case 'SD':
          return '\uD83C\uDDF8\uD83C\uDDE9'
        case 'SE':
          return '\uD83C\uDDF8\uD83C\uDDEA'
        case 'SG':
          return '\uD83C\uDDF8\uD83C\uDDEC'
        case 'SH':
          return '\uD83C\uDDF8\uD83C\uDDED'
        case 'SI':
          return '\uD83C\uDDF8\uD83C\uDDEE'
        case 'SJ':
          return '\uD83C\uDDF8\uD83C\uDDEF'
        case 'SK':
          return '\uD83C\uDDF8\uD83C\uDDF0'
        case 'SL':
          return '\uD83C\uDDF8\uD83C\uDDF1'
        case 'SM':
          return '\uD83C\uDDF8\uD83C\uDDF2'
        case 'SN':
          return '\uD83C\uDDF8\uD83C\uDDF3'
        case 'SO':
          return '\uD83C\uDDF8\uD83C\uDDF4'
        case 'SR':
          return '\uD83C\uDDF8\uD83C\uDDF7'
        case 'SS':
          return '\uD83C\uDDF8\uD83C\uDDF8'
        case 'ST':
          return '\uD83C\uDDF8\uD83C\uDDF9'
        case 'SV':
          return '\uD83C\uDDF8\uD83C\uDDFB'
        case 'SX':
          return '\uD83C\uDDF8\uD83C\uDDFD'
        case 'SY':
          return '\uD83C\uDDF8\uD83C\uDDFE'
        case 'SZ':
          return '\uD83C\uDDF8\uD83C\uDDFF'
        case 'TC':
          return '\uD83C\uDDF9\uD83C\uDDE8'
        case 'TD':
          return '\uD83C\uDDF9\uD83C\uDDE9'
        case 'TF':
          return '\uD83C\uDDF9\uD83C\uDDEB'
        case 'TG':
          return '\uD83C\uDDF9\uD83C\uDDEC'
        case 'TH':
          return '\uD83C\uDDF9\uD83C\uDDED'
        case 'TJ':
          return '\uD83C\uDDF9\uD83C\uDDEF'
        case 'TK':
          return '\uD83C\uDDF9\uD83C\uDDF0'
        case 'TL':
          return '\uD83C\uDDF9\uD83C\uDDF1'
        case 'TM':
          return '\uD83C\uDDF9\uD83C\uDDF2'
        case 'TN':
          return '\uD83C\uDDF9\uD83C\uDDF3'
        case 'TO':
          return '\uD83C\uDDF9\uD83C\uDDF4'
        case 'TR':
          return '\uD83C\uDDF9\uD83C\uDDF7'
        case 'TT':
          return '\uD83C\uDDF9\uD83C\uDDF9'
        case 'TV':
          return '\uD83C\uDDF9\uD83C\uDDFB'
        case 'TW':
          return '\uD83C\uDDF9\uD83C\uDDFC'
        case 'TZ':
          return '\uD83C\uDDF9\uD83C\uDDFF'
        case 'UA':
          return '\uD83C\uDDFA\uD83C\uDDE6'
        case 'UG':
          return '\uD83C\uDDFA\uD83C\uDDEC'
        case 'UM':
          return '\uD83C\uDDFA\uD83C\uDDF2'
        case 'US':
          return '\uD83C\uDDFA\uD83C\uDDF8'
        case 'UY':
          return '\uD83C\uDDFA\uD83C\uDDFE'
        case 'UZ':
          return '\uD83C\uDDFA\uD83C\uDDFF'
        case 'VA':
          return '\uD83C\uDDFB\uD83C\uDDE6'
        case 'VC':
          return '\uD83C\uDDFB\uD83C\uDDE8'
        case 'VE':
          return '\uD83C\uDDFB\uD83C\uDDEA'
        case 'VG':
          return '\uD83C\uDDFB\uD83C\uDDEC'
        case 'VI':
          return '\uD83C\uDDFB\uD83C\uDDEE'
        case 'VN':
          return '\uD83C\uDDFB\uD83C\uDDF3'
        case 'VU':
          return '\uD83C\uDDFB\uD83C\uDDFA'
        case 'WF':
          return '\uD83C\uDDFC\uD83C\uDDEB'
        case 'WS':
          return '\uD83C\uDDFC\uD83C\uDDF8'
        case 'XK':
          return '\uD83C\uDDFD\uD83C\uDDF0'
        case 'YE':
          return '\uD83C\uDDFE\uD83C\uDDEA'
        case 'YT':
          return '\uD83C\uDDFE\uD83C\uDDF9'
        case 'ZA':
          return '\uD83C\uDDFF\uD83C\uDDE6'
        case 'ZM':
          return '\uD83C\uDDFF\uD83C\uDDF2'
        default:
          return '\uD83C\uDFF3'
      }
    },
  }
  return _0x255909
}
